const mongoose = require('mongoose');

const studyBlockSchema = new mongoose.Schema({
  subjectId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Subject',
    required: true
  },
  startTime: {
    type: String,
    required: true
  },
  endTime: {
    type: String,
    required: true
  },
  duration: {
    type: Number, // in minutes
    required: true
  },
  topic: {
    type: String,
    trim: true
  },
  isCompleted: {
    type: Boolean,
    default: false
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high'],
    default: 'medium'
  }
}, { _id: false });

const studyPlanSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  date: {
    type: Date,
    required: true
  },
  studyBlocks: [studyBlockSchema],
  totalStudyTime: {
    type: Number, // in minutes
    default: 0
  },
  completedStudyTime: {
    type: Number, // in minutes
    default: 0
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

// Update updatedAt on save
studyPlanSchema.pre('save', function(next) {
  this.updatedAt = Date.now();
  
  // Calculate total study time
  this.totalStudyTime = this.studyBlocks.reduce((total, block) => {
    return total + block.duration;
  }, 0);
  
  // Calculate completed study time
  this.completedStudyTime = this.studyBlocks.reduce((total, block) => {
    return total + (block.isCompleted ? block.duration : 0);
  }, 0);
  
  next();
});

// Virtual for progress percentage
studyPlanSchema.virtual('progressPercentage').get(function() {
  if (this.totalStudyTime === 0) return 0;
  return Math.round((this.completedStudyTime / this.totalStudyTime) * 100);
});

studyPlanSchema.set('toJSON', { virtuals: true });
studyPlanSchema.set('toObject', { virtuals: true });

// Index for efficient queries
studyPlanSchema.index({ userId: 1, date: 1 });

module.exports = mongoose.model('StudyPlan', studyPlanSchema);
